# Target Varialbe : Tip

In [1]:
!cd

C:\Users\admin\Desktop\데이터 공부 자료\day20\2021-K-Digital-Training-main\SQL


In [2]:
#!pip install PyMySQL==1.0.0

In [3]:
import pymysql.cursors
# Connect to the database

In [4]:
import pandas as pd

In [5]:
import pandas_profiling

In [6]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost', user='me', 
                       password='9421', db='tip', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "select * from tips;"
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
    
      df.to_csv('query.csv')

finally:

   conn.close()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner   2.0
1         10.34  1.66    Male     No   Sun  Dinner   3.0
2         21.01  3.50    Male     No   Sun  Dinner   3.0
3         23.68  3.31    Male     No   Sun  Dinner   2.0
4         24.59  3.61  Female     No   Sun  Dinner   4.0
..          ...   ...     ...    ...   ...     ...   ...
245        3.07  1.00  Female    Yes   Sat  Dinner   3.0
246        3.07  1.00  Female    Yes  None  Dinner   3.0
247        3.07  1.00  Female    Yes  None  Dinner   NaN
248        3.07  1.00    None    Yes   Sun  Dinner   NaN
249        3.07  1.00  Female    Yes   Sun  Dinner   NaN

[250 rows x 7 columns]


# Encoding

In [7]:
df['sex'].replace({'Female':0,'Male':1},inplace=True)

In [8]:
df['smoker'].replace({'No':0,'Yes':1},inplace=True)

In [9]:
df["day"].replace({"Thur" : 0, "Fri" : 1, "Sat" : 2, "Sun" : 3},inplace=True)

In [10]:
df['time'].replace({'Lunch':0,'Dinner':1},inplace=True)

In [11]:
df.isnull().sum()         #data frame에서 nan 찾기

total_bill    0
tip           0
sex           1
smoker        0
day           2
time          0
size          3
dtype: int64

In [12]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  250.000000  250.000000  249.000000  250.000000  248.000000  250.000000   
mean    19.440440    2.950360    0.630522    0.392000    1.741935    0.728000   
std      9.103058    1.400742    0.483636    0.489176    1.154964    0.445883   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.137500    2.000000    0.000000    0.000000    0.750000    0.000000   
50%     17.490000    2.750000    1.000000    0.000000    2.000000    1.000000   
75%     24.047500    3.507500    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size  
count  247.000000  
mean     2.570850  
std      0.946775  
min      1.000000  
25%      2.000000  
50%      2.000000  
75%      3.000000  
max      6.000000

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
import numpy as np
from sklearn.impute import SimpleImputer

In [15]:
data=df.values           #data frame -> array로 바꾸기

In [16]:
datas=df.values         #pca를 위해 넣은 값

In [17]:
y=df['total_bill']       #구하고자 하는 값

In [18]:
X=df.drop('total_bill',axis=1) #구하고자 하는 값 제외한 것은 모두 넣고 비교

In [19]:
X.describe()

tip         sex      smoker         day        time        size
count  250.000000  249.000000  250.000000  248.000000  250.000000  247.000000
mean     2.950360    0.630522    0.392000    1.741935    0.728000    2.570850
std      1.400742    0.483636    0.489176    1.154964    0.445883    0.946775
min      1.000000    0.000000    0.000000    0.000000    0.000000    1.000000
25%      2.000000    0.000000    0.000000    0.750000    0.000000    2.000000
50%      2.750000    1.000000    0.000000    2.000000    1.000000    2.000000
75%      3.507500    1.000000    1.000000    3.000000    1.000000    3.000000
max     10.000000    1.000000    1.000000    3.000000    1.000000    6.000000

In [20]:
X.columns

Index(['tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [21]:
y.describe()

count    250.000000
mean      19.440440
std        9.103058
min        3.070000
25%       13.137500
50%       17.490000
75%       24.047500
max       50.810000
Name: total_bill, dtype: float64

In [22]:
data=X.values

In [23]:
y=y.values

In [24]:
data

array([[1.01, 0.  , 0.  , 3.  , 1.  , 2.  ],
       [1.66, 1.  , 0.  , 3.  , 1.  , 3.  ],
       [3.5 , 1.  , 0.  , 3.  , 1.  , 3.  ],
       ...,
       [1.  , 0.  , 1.  ,  nan, 1.  ,  nan],
       [1.  ,  nan, 1.  , 3.  , 1.  ,  nan],
       [1.  , 0.  , 1.  , 3.  , 1.  ,  nan]])

In [25]:
data.shape

(250, 6)

In [26]:
data[:,-1]

array([ 2.,  3.,  3.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  4.,  2.,
        4.,  2.,  2.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  4.,  2.,  4.,
        2.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,  3.,  3.,  3.,  3.,
        3.,  3.,  2.,  2.,  2.,  4.,  2.,  2.,  4.,  3.,  2.,  2.,  2.,
        4.,  2.,  4.,  2.,  4.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  4.,
        2.,  2.,  2.,  2.,  1.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  3.,  2.,  3.,  2.,  4.,
        2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  6.,  2.,  2.,  2.,  3.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  5.,
        6.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  4.,  4.,  5.,
        6.,  4.,  2.,  4.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  4.,  2.,
        2.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  4

In [27]:
sum(np.isnan(data).flatten())          #array에서 nan값 찾기

6

In [28]:
imputer = SimpleImputer(strategy='median')

In [29]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [30]:
datatrans = imputer.transform(data)

In [31]:
datatrans[:,-1]

array([2., 3., 3., 2., 4., 4., 2., 4., 2., 2., 2., 4., 2., 4., 2., 2., 3.,
       3., 3., 3., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 4., 2., 4.,
       2., 3., 3., 3., 3., 3., 3., 2., 2., 2., 4., 2., 2., 4., 3., 2., 2.,
       2., 4., 2., 4., 2., 4., 2., 2., 4., 2., 2., 2., 4., 3., 3., 2., 1.,
       2., 2., 2., 3., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 1., 2., 2.,
       4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 1., 3., 2., 3., 2., 4., 2., 2.,
       4., 2., 2., 2., 2., 2., 6., 2., 2., 2., 3., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 6., 5., 6., 2., 2., 3., 2., 2., 2., 2., 2., 3.,
       4., 4., 5., 6., 4., 2., 4., 4., 2., 3., 2., 2., 3., 2., 4., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 3., 4., 2., 5., 3.,
       5., 3., 3., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 3., 2., 2., 2.,
       4., 3., 3., 4., 2., 2., 3., 4., 4., 2., 3., 2., 5., 2., 2., 4., 2.,
       2., 1., 3., 2., 2.

In [32]:
df_trans=pd.DataFrame(datatrans)

In [33]:
df_trans.isnull()

0      1      2      3      4      5
0    False  False  False  False  False  False
1    False  False  False  False  False  False
2    False  False  False  False  False  False
3    False  False  False  False  False  False
4    False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...
245  False  False  False  False  False  False
246  False  False  False  False  False  False
247  False  False  False  False  False  False
248  False  False  False  False  False  False
249  False  False  False  False  False  False

[250 rows x 6 columns]

In [34]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64

In [35]:
df_trans.columns=['tip', 'sex', 'smoker', 'day', 'time', 'size']

In [36]:
df_trans.describe().round()

tip    sex  smoker    day   time   size
count  250.0  250.0   250.0  250.0  250.0  250.0
mean     3.0    1.0     0.0    2.0    1.0    3.0
std      1.0    0.0     0.0    1.0    0.0    1.0
min      1.0    0.0     0.0    0.0    0.0    1.0
25%      2.0    0.0     0.0    1.0    0.0    2.0
50%      3.0    1.0     0.0    2.0    1.0    2.0
75%      4.0    1.0     1.0    3.0    1.0    3.0
max     10.0    1.0     1.0    3.0    1.0    6.0

In [37]:
df_trans.profile_report()

Summarize dataset:   0%|          | 0/19 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

#### 이 밑의 부분은 PCA를 위해 만든 것이다. `y=df['total_bill'] ` 와 'X=df.drop('total_bill',axis=1)' 영향이 없는 새로운 변수들을 만들었다. 기존변수에 `+s` 형태를 취한다.

In [38]:
sum(np.isnan(datas).flatten())  

6

In [39]:
imputers = SimpleImputer(strategy='median')

In [40]:
imputers.fit(datas)

SimpleImputer(strategy='median')

In [41]:
datatranss = imputers.transform(datas)

In [42]:
datatranss[:,-2]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [43]:
df_transs=pd.DataFrame(datatranss)

In [44]:
df_transs.isnull()

0      1      2      3      4      5      6
0    False  False  False  False  False  False  False
1    False  False  False  False  False  False  False
2    False  False  False  False  False  False  False
3    False  False  False  False  False  False  False
4    False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...
245  False  False  False  False  False  False  False
246  False  False  False  False  False  False  False
247  False  False  False  False  False  False  False
248  False  False  False  False  False  False  False
249  False  False  False  False  False  False  False

[250 rows x 7 columns]

In [45]:
df_transs.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

# RFE

#### 차원축소

In [46]:
from sklearn.feature_selection import RFE
#from sklearn.tree import DecisionTreeClassifier   #classical 변수인 경우 사용

In [47]:
from sklearn.svm import SVR  #numerical 변수인 경우 사용

In [48]:
estimator=SVR(kernel="linear")

In [49]:
# define RFE
rfe = RFE(estimator, n_features_to_select=4) #변수 6개 중 4개 가지기

In [50]:
y.shape

(250,)

In [51]:
# fit RFE
selecto=rfe.fit(datatrans, y)

In [52]:
# transform the data
rselecto= rfe.fit_transform(datatrans, y)    #이 과정이 들어있어야 DataFrame 가능

In [53]:
selecto.support_

array([ True, False, False,  True,  True,  True])

In [54]:
# fit RFE
selecto=rfe.fit(datatrans, y)

In [55]:
selecto.support_

array([ True, False, False,  True,  True,  True])

In [56]:
X.head(3)   #1,2이 False 즉, sex,smoker가 빠졌다.

tip  sex  smoker  day  time  size
0  1.01  0.0       0  3.0     1   2.0
1  1.66  1.0       0  3.0     1   3.0
2  3.50  1.0       0  3.0     1   3.0

In [57]:
# summarize all features
for i in range(X.shape[1]):
  print('Column: %d, Selected=%s, Rank: %d' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected=True, Rank: 1
Column: 1, Selected=False, Rank: 3
Column: 2, Selected=False, Rank: 2
Column: 3, Selected=True, Rank: 1
Column: 4, Selected=True, Rank: 1
Column: 5, Selected=True, Rank: 1


In [58]:
Selecto=pd.DataFrame(rselecto)

In [59]:
Selecto.describe().round()

0      1      2      3
count  250.0  250.0  250.0  250.0
mean     3.0    2.0    1.0    3.0
std      1.0    1.0    0.0    1.0
min      1.0    0.0    0.0    1.0
25%      2.0    1.0    0.0    2.0
50%      3.0    2.0    1.0    2.0
75%      4.0    3.0    1.0    3.0
max     10.0    3.0    1.0    6.0

In [60]:
Selecto.columns=['tip','day','time','size']

In [61]:
Selecto.describe().round()

tip    day   time   size
count  250.0  250.0  250.0  250.0
mean     3.0    2.0    1.0    3.0
std      1.0    1.0    0.0    1.0
min      1.0    0.0    0.0    1.0
25%      2.0    1.0    0.0    2.0
50%      3.0    2.0    1.0    2.0
75%      4.0    3.0    1.0    3.0
max     10.0    3.0    1.0    6.0

In [62]:
Selecto.profile_report()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# MinMaxScaler

#### 최소값(Min)과 최대값(Max)을 사용해서 '0~1'사이의 범위로 데이터를 표준화

In [63]:
from sklearn.preprocessing import MinMaxScaler

In [64]:
trans = MinMaxScaler()

In [65]:
data.shape

(250, 6)

In [66]:
X_norm = trans.fit_transform(data)

In [67]:
df_norm=pd.DataFrame(X_norm)

In [68]:
df_norm.describe().round()

0      1      2      3      4      5
count  250.0  249.0  250.0  248.0  250.0  247.0
mean     0.0    1.0    0.0    1.0    1.0    0.0
std      0.0    0.0    0.0    0.0    0.0    0.0
min      0.0    0.0    0.0    0.0    0.0    0.0
25%      0.0    0.0    0.0    0.0    0.0    0.0
50%      0.0    1.0    0.0    1.0    1.0    0.0
75%      0.0    1.0    1.0    1.0    1.0    0.0
max      1.0    1.0    1.0    1.0    1.0    1.0

# Data Standardization

#### 정규화과정으로 평균을 0, 분산을 1로 만든다.

In [69]:
from sklearn.preprocessing import StandardScaler

In [70]:
sc = StandardScaler()

In [71]:
df_sc=sc.fit_transform(data)

In [72]:
df_trsfrom_sc=pd.DataFrame(df_sc)

In [73]:
df_trsfrom_sc.describe().round() #정규화가 끝나서 평균0, 분산1

0      1      2      3      4      5
count  250.0  249.0  250.0  248.0  250.0  247.0
mean     0.0    0.0    0.0    0.0    0.0   -0.0
std      1.0    1.0    1.0    1.0    1.0    1.0
min     -1.0   -1.0   -1.0   -2.0   -2.0   -2.0
25%     -1.0   -1.0   -1.0   -1.0   -2.0   -1.0
50%     -0.0    1.0   -1.0    0.0    1.0   -1.0
75%      0.0    1.0    1.0    1.0    1.0    0.0
max      5.0    1.0    1.0    1.0    1.0    4.0

# PCA 주성분 분석

#### 각 변수에서 주된 성분을 뽑아서 분석해준다.

#### pca는 자체적으로 공분산값을 구해서 아이겐벨류값을 얻어서 그걸 비교해서 위에서 부터 큰값을 리턴한다


#### pca는 값을 타겟하는 과정이  필요없는 함수이다. 따라서 위의 과정처럼 `y=df['total_bill'] ` 과 `X=df.drop('total_bill',axis=1)`가 필요없다. 그래서 `y=df['total_bill'] ` 과 `X=df.drop('total_bill',axis=1)`의 영향이 없는 `datatranss`를 이용하였다.

In [74]:
from sklearn.decomposition import PCA

In [75]:
# define the transform
trans = PCA(n_components=4)  #주성분을 4개 골라준다.

In [76]:
# transform the data
X_dim = trans.fit_transform(datatranss)

In [77]:
# summarize data after the transform
print(X_dim[:3, :]) #X_dim은 array라서 describe(),info() 불가

[[-2.65377891e+00 -1.16287742e+00  1.75653688e+00 -4.54319088e-03]
 [-9.11291684e+00 -1.56431123e+00  1.56985109e-01  9.62381454e-01]
 [ 1.67026036e+00 -1.31440221e+00 -3.87399491e-01  2.06880629e-01]]


In [78]:
trans.components_  

array([[ 0.99219958,  0.10674331,  0.00910047,  0.00185638,  0.01848725,
         0.00754219,  0.06050565],
       [ 0.03026348, -0.03967518, -0.08736415,  0.01426274, -0.93649885,
        -0.32414503, -0.08702864],
       [ 0.11553592, -0.96584393,  0.0111308 ,  0.06068503,  0.05253978,
         0.03449061, -0.21457018],
       [-0.03079299, -0.2320324 , -0.03781029, -0.18048838, -0.05690186,
        -0.06310066,  0.95078261]])

In [79]:
trans.explained_variance_           #주성분의 분산값

array([84.15764798,  1.46442885,  1.04002092,  0.56848252])

In [80]:
trans.explained_variance_ratio_     #주성분의 분산값의 비율

array([0.95947063, 0.01669577, 0.01185715, 0.0064812 ])

In [81]:
trans.explained_variance_ratio_.cumsum() #각 행마다의 데이터 분포값을 더해주기

array([0.95947063, 0.9761664 , 0.98802354, 0.99450474])

In [82]:
trans.explained_variance_ratio_.sum()     #주성분의 분산값의 비율의 총합
                                          #전체 데이터에서 얼마를 대표하는 지 

0.9945047412614128

In [83]:
x_dim=pd.DataFrame(X_dim)

In [84]:
x_dim.describe().round()

0      1      2      3
count  250.0  250.0  250.0  250.0
mean     0.0    0.0    0.0   -0.0
std      9.0    1.0    1.0    1.0
min    -17.0   -2.0   -3.0   -2.0
25%     -6.0   -1.0   -0.0   -0.0
50%     -2.0   -0.0    0.0   -0.0
75%      5.0    1.0    0.0    0.0
max     32.0    2.0    3.0    3.0

In [85]:
x_dim.profile_report()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Regression Feature Selection

#### 수치형 종속변수와 수치형 독립변수사이의 영향 또는 인과관계를 알 수 있는 분석
#### 상관관계 -> 인과관계로 바꿔주는 함수.(통계학과 수업시간에 배움..)

In [86]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [87]:
# define feature selection
fs = SelectKBest(score_func=f_regression, k=4)  #7개 변수 중 4개만 취한다.

In [88]:
datatrans.shape

(250, 6)

In [89]:
y.shape

(250,)

In [90]:
# apply feature selection / 행이 같으므로 값이 나온다.
X_selected = fs.fit_transform(datatrans, y)

In [91]:
fs.get_support(indices=True)   # 6개의 행 중에서 0,1,4,5만 취한다.

array([0, 1, 4, 5], dtype=int64)

In [92]:
fs.get_support(indices=False)  # 6개의 행 중에서 2,3을 뺀다.

array([ True,  True, False, False,  True,  True])

In [93]:
X.head(3)                      #즉 tip,sex,time,size를 살린다.

tip  sex  smoker  day  time  size
0  1.01  0.0       0  3.0     1   2.0
1  1.66  1.0       0  3.0     1   3.0
2  3.50  1.0       0  3.0     1   3.0

In [94]:
print(X_selected.shape)

(250, 4)


In [95]:
X_selected.shape[1]

4

In [96]:
x_selexted=pd.DataFrame(X_selected)

In [97]:
x_selexted.describe()

0           1           2           3
count  250.000000  250.000000  250.000000  250.000000
mean     2.950360    0.632000    0.728000    2.564000
std      1.400742    0.483229    0.445883    0.943113
min      1.000000    0.000000    0.000000    1.000000
25%      2.000000    0.000000    0.000000    2.000000
50%      2.750000    1.000000    1.000000    2.000000
75%      3.507500    1.000000    1.000000    3.000000
max     10.000000    1.000000    1.000000    6.000000

In [98]:
df_rfe_selected = pd.DataFrame(X_selected, columns=['tip', 'sex',  'time', 'size'])

In [99]:
df_rfe_selected.describe()

tip         sex        time        size
count  250.000000  250.000000  250.000000  250.000000
mean     2.950360    0.632000    0.728000    2.564000
std      1.400742    0.483229    0.445883    0.943113
min      1.000000    0.000000    0.000000    1.000000
25%      2.000000    0.000000    0.000000    2.000000
50%      2.750000    1.000000    1.000000    2.000000
75%      3.507500    1.000000    1.000000    3.000000
max     10.000000    1.000000    1.000000    6.000000

In [100]:
df_rfe_selected.profile_report()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

#### rfe는 독립변수들과 목표변수와의 관계를 통해 차원을 축소시키고
#### pca는 독립변수들끼리의 상관관계만으로만 차원을 축소시킨다.