# Target Varialbe : Tip

In [1]:
!cd

C:\Users\admin\Desktop\데이터 공부 자료\day20\2021-K-Digital-Training-main\SQL


In [2]:
#!pip install PyMySQL==1.0.0

In [3]:
import pymysql.cursors
# Connect to the database

In [4]:
import pandas as pd

In [5]:
# MySQL DB에서 데이터 받아와서 DataFrame에 저장

conn = pymysql.connect(host='localhost', user='me', 
                       password='9421', db='tip', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "select * from tips;"
      curs.execute(sql)
      rs = curs.fetchall()

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
    
      df.to_csv('query.csv')

finally:

   conn.close()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner   2.0
1         10.34  1.66    Male     No   Sun  Dinner   3.0
2         21.01  3.50    Male     No   Sun  Dinner   3.0
3         23.68  3.31    Male     No   Sun  Dinner   2.0
4         24.59  3.61  Female     No   Sun  Dinner   4.0
..          ...   ...     ...    ...   ...     ...   ...
245        3.07  1.00  Female    Yes   Sat  Dinner   3.0
246        3.07  1.00  Female    Yes  None  Dinner   3.0
247        3.07  1.00  Female    Yes  None  Dinner   NaN
248        3.07  1.00    None    Yes   Sun  Dinner   NaN
249        3.07  1.00  Female    Yes   Sun  Dinner   NaN

[250 rows x 7 columns]


In [6]:
df=df.assign(tip_rate=((df["tip"] / df["total_bill"])*100).round(2))

In [7]:
df

total_bill   tip     sex smoker   day    time  size  tip_rate
0         16.99  1.01  Female     No   Sun  Dinner   2.0      5.94
1         10.34  1.66    Male     No   Sun  Dinner   3.0     16.05
2         21.01  3.50    Male     No   Sun  Dinner   3.0     16.66
3         23.68  3.31    Male     No   Sun  Dinner   2.0     13.98
4         24.59  3.61  Female     No   Sun  Dinner   4.0     14.68
..          ...   ...     ...    ...   ...     ...   ...       ...
245        3.07  1.00  Female    Yes   Sat  Dinner   3.0     32.57
246        3.07  1.00  Female    Yes  None  Dinner   3.0     32.57
247        3.07  1.00  Female    Yes  None  Dinner   NaN     32.57
248        3.07  1.00    None    Yes   Sun  Dinner   NaN     32.57
249        3.07  1.00  Female    Yes   Sun  Dinner   NaN     32.57

[250 rows x 8 columns]

# Encoding

In [8]:
df['sex'].replace({'Female':0,'Male':1},inplace=True)

In [9]:
df['smoker'].replace({'No':0,'Yes':1},inplace=True)

In [10]:
df["day"].replace({"Thur" : 0, "Fri" : 1, "Sat" : 2, "Sun" : 3},inplace=True)

In [11]:
df['time'].replace({'Lunch':0,'Dinner':1},inplace=True)

In [12]:
df.isnull().sum()         #data frame에서 nan 찾기

total_bill    0
tip           0
sex           1
smoker        0
day           2
time          0
size          3
tip_rate      0
dtype: int64

In [13]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  250.000000  250.000000  249.000000  250.000000  248.000000  250.000000   
mean    19.440440    2.950360    0.630522    0.392000    1.741935    0.728000   
std      9.103058    1.400742    0.483636    0.489176    1.154964    0.445883   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.137500    2.000000    0.000000    0.000000    0.750000    0.000000   
50%     17.490000    2.750000    1.000000    0.000000    2.000000    1.000000   
75%     24.047500    3.507500    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  247.000000  250.000000  
mean     2.570850   16.369000  
std      0.946775    6.495099  
min      1.000000    3.560000  
25%      2.000000   12.960000  
50%      2.000000   15.560000  
75%      3.000000   19.335000  
max      6.000000   71.030000

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
import numpy as np
from sklearn.impute import SimpleImputer

In [16]:
data=df.values           #data frame -> array로 바꾸기

In [17]:
y=df['tip']       #구하고자 하는 값

In [18]:
X=df.drop('tip',axis=1) #구하고자 하는 값 제외한 것은 모두 넣고 비교

In [19]:
X.describe()

total_bill         sex      smoker         day        time        size  \
count  250.000000  249.000000  250.000000  248.000000  250.000000  247.000000   
mean    19.440440    0.630522    0.392000    1.741935    0.728000    2.570850   
std      9.103058    0.483636    0.489176    1.154964    0.445883    0.946775   
min      3.070000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%     13.137500    0.000000    0.000000    0.750000    0.000000    2.000000   
50%     17.490000    1.000000    0.000000    2.000000    1.000000    2.000000   
75%     24.047500    1.000000    1.000000    3.000000    1.000000    3.000000   
max     50.810000    1.000000    1.000000    3.000000    1.000000    6.000000   

         tip_rate  
count  250.000000  
mean    16.369000  
std      6.495099  
min      3.560000  
25%     12.960000  
50%     15.560000  
75%     19.335000  
max     71.030000

In [20]:
X.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [21]:
y.describe()

count    250.000000
mean       2.950360
std        1.400742
min        1.000000
25%        2.000000
50%        2.750000
75%        3.507500
max       10.000000
Name: tip, dtype: float64

In [22]:
data=X.values

In [23]:
y=y.values

In [24]:
data

array([[16.99,  0.  ,  0.  , ...,  1.  ,  2.  ,  5.94],
       [10.34,  1.  ,  0.  , ...,  1.  ,  3.  , 16.05],
       [21.01,  1.  ,  0.  , ...,  1.  ,  3.  , 16.66],
       ...,
       [ 3.07,  0.  ,  1.  , ...,  1.  ,   nan, 32.57],
       [ 3.07,   nan,  1.  , ...,  1.  ,   nan, 32.57],
       [ 3.07,  0.  ,  1.  , ...,  1.  ,   nan, 32.57]])

In [25]:
data.shape

(250, 7)

In [26]:
data[:,-2]

array([ 2.,  3.,  3.,  2.,  4.,  4.,  2.,  4.,  2.,  2.,  2.,  4.,  2.,
        4.,  2.,  2.,  3.,  3.,  3.,  3.,  2.,  2.,  2.,  4.,  2.,  4.,
        2.,  2.,  2.,  2.,  2.,  4.,  2.,  4.,  2.,  3.,  3.,  3.,  3.,
        3.,  3.,  2.,  2.,  2.,  4.,  2.,  2.,  4.,  3.,  2.,  2.,  2.,
        4.,  2.,  4.,  2.,  4.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  4.,
        2.,  2.,  2.,  2.,  1.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  3.,  2.,  3.,  2.,  4.,
        2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  6.,  2.,  2.,  2.,  3.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  6.,  5.,
        6.,  2.,  2.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  4.,  4.,  5.,
        6.,  4.,  2.,  4.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  4.,  2.,
        2.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  4

In [27]:
sum(np.isnan(data).flatten())          #array에서 nan값 찾기

6

In [28]:
imputer = SimpleImputer(strategy='median')

In [29]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [30]:
datatrans = imputer.transform(data)

In [31]:
datatrans[:,-2]

array([2., 3., 3., 2., 4., 4., 2., 4., 2., 2., 2., 4., 2., 4., 2., 2., 3.,
       3., 3., 3., 2., 2., 2., 4., 2., 4., 2., 2., 2., 2., 2., 4., 2., 4.,
       2., 3., 3., 3., 3., 3., 3., 2., 2., 2., 4., 2., 2., 4., 3., 2., 2.,
       2., 4., 2., 4., 2., 4., 2., 2., 4., 2., 2., 2., 4., 3., 3., 2., 1.,
       2., 2., 2., 3., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 1., 2., 2.,
       4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 1., 3., 2., 3., 2., 4., 2., 2.,
       4., 2., 2., 2., 2., 2., 6., 2., 2., 2., 3., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 6., 5., 6., 2., 2., 3., 2., 2., 2., 2., 2., 3.,
       4., 4., 5., 6., 4., 2., 4., 4., 2., 3., 2., 2., 3., 2., 4., 2., 2.,
       3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 3., 4., 2., 5., 3.,
       5., 3., 3., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 3., 2., 2., 2.,
       4., 3., 3., 4., 2., 2., 3., 4., 4., 2., 3., 2., 5., 2., 2., 4., 2.,
       2., 1., 3., 2., 2.

In [32]:
df_trans=pd.DataFrame(datatrans)

In [33]:
df_trans.isnull()

0      1      2      3      4      5      6
0    False  False  False  False  False  False  False
1    False  False  False  False  False  False  False
2    False  False  False  False  False  False  False
3    False  False  False  False  False  False  False
4    False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...
245  False  False  False  False  False  False  False
246  False  False  False  False  False  False  False
247  False  False  False  False  False  False  False
248  False  False  False  False  False  False  False
249  False  False  False  False  False  False  False

[250 rows x 7 columns]

In [34]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

# RFE

#### 차원축소

In [35]:
from sklearn.feature_selection import RFE
#from sklearn.tree import DecisionTreeClassifier   #classical 변수인 경우 사용

In [36]:
from sklearn.svm import SVR  #numerical 변수인 경우 사용

In [37]:
estimator=SVR(kernel="linear")

In [38]:
# define RFE
rfe = RFE(estimator, n_features_to_select=4) #변수 7개 중 4개 가지기

In [39]:
y.shape

(250,)

In [40]:
# fit RFE
selecto=rfe.fit(datatrans, y)

In [41]:
selecto.support_

array([ True,  True,  True, False, False, False,  True])

In [42]:
X.head(3)   #4,5,6이 False 즉, day와 time,size가 빠졌다.

total_bill  sex  smoker  day  time  size  tip_rate
0       16.99  0.0       0  3.0     1   2.0      5.94
1       10.34  1.0       0  3.0     1   3.0     16.05
2       21.01  1.0       0  3.0     1   3.0     16.66

In [43]:
# summarize all features
for i in range(X.shape[1]):
  print('Column: %d, Selected=%s, Rank: %d' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected=True, Rank: 1
Column: 1, Selected=True, Rank: 1
Column: 2, Selected=True, Rank: 1
Column: 3, Selected=False, Rank: 4
Column: 4, Selected=False, Rank: 3
Column: 5, Selected=False, Rank: 2
Column: 6, Selected=True, Rank: 1


In [44]:
df1=pd.DataFrame(datatrans)

In [45]:
df1

0    1    2    3    4    5      6
0    16.99  0.0  0.0  3.0  1.0  2.0   5.94
1    10.34  1.0  0.0  3.0  1.0  3.0  16.05
2    21.01  1.0  0.0  3.0  1.0  3.0  16.66
3    23.68  1.0  0.0  3.0  1.0  2.0  13.98
4    24.59  0.0  0.0  3.0  1.0  4.0  14.68
..     ...  ...  ...  ...  ...  ...    ...
245   3.07  0.0  1.0  2.0  1.0  3.0  32.57
246   3.07  0.0  1.0  2.0  1.0  3.0  32.57
247   3.07  0.0  1.0  2.0  1.0  2.0  32.57
248   3.07  1.0  1.0  3.0  1.0  2.0  32.57
249   3.07  0.0  1.0  3.0  1.0  2.0  32.57

[250 rows x 7 columns]

# MinMaxScaler

#### 최소값(Min)과 최대값(Max)을 사용해서 '0~1'사이의 범위로 데이터를 표준화

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
trans = MinMaxScaler()

In [48]:
data.shape

(250, 7)

In [49]:
X_norm = trans.fit_transform(data)

In [50]:
df_norm=pd.DataFrame(X_norm)

In [51]:
df_norm.describe().round()

0      1      2      3      4      5      6
count  250.0  249.0  250.0  248.0  250.0  247.0  250.0
mean     0.0    1.0    0.0    1.0    1.0    0.0    0.0
std      0.0    0.0    0.0    0.0    0.0    0.0    0.0
min      0.0    0.0    0.0    0.0    0.0    0.0    0.0
25%      0.0    0.0    0.0    0.0    0.0    0.0    0.0
50%      0.0    1.0    0.0    1.0    1.0    0.0    0.0
75%      0.0    1.0    1.0    1.0    1.0    0.0    0.0
max      1.0    1.0    1.0    1.0    1.0    1.0    1.0

# Data Standardization

#### 정규화과정으로 평균을 0, 분산을 1로 만든다.

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
sc = StandardScaler()

In [54]:
df_sc=sc.fit_transform(data)

In [55]:
df_trsfrom_sc=pd.DataFrame(df_sc)

In [56]:
df_trsfrom_sc.describe().round() #정규화가 끝나서 평균0, 분산1

0      1      2      3      4      5      6
count  250.0  249.0  250.0  248.0  250.0  247.0  250.0
mean     0.0    0.0    0.0    0.0    0.0   -0.0    0.0
std      1.0    1.0    1.0    1.0    1.0    1.0    1.0
min     -2.0   -1.0   -1.0   -2.0   -2.0   -2.0   -2.0
25%     -1.0   -1.0   -1.0   -1.0   -2.0   -1.0   -1.0
50%     -0.0    1.0   -1.0    0.0    1.0   -1.0   -0.0
75%      1.0    1.0    1.0    1.0    1.0    0.0    0.0
max      3.0    1.0    1.0    1.0    1.0    4.0    8.0

# PCA 주성분 분석

#### 각 변수에서 주된 성분을 뽑아서 분석해준다.

#### pca는 자체적으로 공분산값을 구해서 아이겐벨류값을 얻어서 그걸 비교해서 위에서 부터 큰값을 리턴한다


In [57]:
from sklearn.decomposition import PCA

In [58]:
# define the transform
trans = PCA(n_components=4)  #주성분을 4개 골라준다.

In [59]:
# transform the data
X_dim = trans.fit_transform(datatrans)

In [60]:
# summarize data after the transform
print(X_dim[:3, :]) #X_dim은 array라서 describe(),info() 불가

[[ -2.04916937 -10.49280679  -1.47554136  -0.25047304]
 [  8.10103182  -3.96415147  -1.62700353   0.96409001]
 [ -1.35306837   0.95993539  -1.28225776   0.31099345]]


In [61]:
trans.components_  

array([[-9.09586020e-01, -8.79077806e-03, -1.96906392e-04,
        -1.38428622e-02, -6.17817021e-03, -5.27983743e-02,
         4.11774809e-01],
       [ 4.09416463e-01,  8.62938544e-04,  1.09121123e-02,
         2.84876089e-02,  8.19444530e-03,  4.18062593e-02,
         9.10841306e-01],
       [ 3.10887860e-02, -9.05915184e-02,  1.85516681e-02,
        -9.37431029e-01, -3.26099614e-01, -7.00602573e-02,
         2.13580646e-02],
       [-6.04885336e-02, -3.18462724e-02, -2.10403281e-01,
        -5.34152592e-02, -6.48855017e-02,  9.71511925e-01,
        -1.25965726e-02]])

In [62]:
trans.explained_variance_           #주성분의 분산값

array([93.7331887 , 31.69147709,  1.44797373,  0.5886354 ])

In [63]:
trans.explained_variance_ratio_     #주성분의 분산값의 비율

array([0.73265217, 0.24771193, 0.01131788, 0.00460099])

In [64]:
trans.explained_variance_ratio_.sum()     #주성분의 분산값의 비율의 총합
                                          #전체 데이터에서 얼마를 대표하는 지 

0.9962829654426311

In [65]:
x_dim=pd.DataFrame(X_dim)

In [66]:
x_dim.describe().round()

0      1      2      3
count  250.0  250.0  250.0  250.0
mean    -0.0    0.0    0.0   -0.0
std     10.0    6.0    1.0    1.0
min    -29.0  -10.0   -2.0   -2.0
25%     -5.0   -4.0   -1.0   -0.0
50%      2.0   -0.0   -0.0   -0.0
75%      6.0    3.0    1.0    0.0
max     34.0   45.0    2.0    3.0

# Regression Feature Selection

#### 수치형 종속변수와 수치형 독립변수사이의 영향 또는 인과관계를 알 수 있는 분석
#### 상관관계 -> 인과관계로 바꿔주는 함수.(통계학과 수업시간에 배움..)

In [67]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [68]:
# define feature selection
fs = SelectKBest(score_func=f_regression, k=4)  #7개 변수 중 4개만 취한다.

In [69]:
datatrans.shape

(250, 7)

In [70]:
y.shape

(250,)

In [71]:
# apply feature selection / 행이 같으므로 값이 나온다.
X_selected = fs.fit_transform(datatrans, y)

In [72]:
fs.get_support(indices=True)   # 7개의 행 중에서 0,1,5,6만 취한다.

array([0, 1, 5, 6], dtype=int64)

In [73]:
fs.get_support(indices=False)  # 6개의 행 중에서 2,3,4를 뺀다.

array([ True,  True, False, False, False,  True,  True])

In [74]:
X.head(3)                      #즉 total_bill,sex,size,tip_rate를 살린다.

total_bill  sex  smoker  day  time  size  tip_rate
0       16.99  0.0       0  3.0     1   2.0      5.94
1       10.34  1.0       0  3.0     1   3.0     16.05
2       21.01  1.0       0  3.0     1   3.0     16.66

In [75]:
print(X_selected.shape)

(250, 4)


In [76]:
X_selected.shape[1]

4

In [77]:
x_selexted=pd.DataFrame(X_selected)

In [78]:
x_selexted.describe()

0           1           2           3
count  250.000000  250.000000  250.000000  250.000000
mean    19.440440    0.632000    2.564000   16.369000
std      9.103058    0.483229    0.943113    6.495099
min      3.070000    0.000000    1.000000    3.560000
25%     13.137500    0.000000    2.000000   12.960000
50%     17.490000    1.000000    2.000000   15.560000
75%     24.047500    1.000000    3.000000   19.335000
max     50.810000    1.000000    6.000000   71.030000

In [79]:
df_rfe_selected = pd.DataFrame(X_selected, columns=['total_bill', 'sex',  'size', 'tip_rate'])

In [80]:
df_rfe_selected.describe()

total_bill         sex        size    tip_rate
count  250.000000  250.000000  250.000000  250.000000
mean    19.440440    0.632000    2.564000   16.369000
std      9.103058    0.483229    0.943113    6.495099
min      3.070000    0.000000    1.000000    3.560000
25%     13.137500    0.000000    2.000000   12.960000
50%     17.490000    1.000000    2.000000   15.560000
75%     24.047500    1.000000    3.000000   19.335000
max     50.810000    1.000000    6.000000   71.030000

#### rfe는 독립변수들과 목표변수와의 관계를 통해 차원을 축소시키고
#### pca는 독립변수들끼리의 상관관계만으로만 차원을 축소시킨다.